### ISSUE TITLE
i need help in adding this to my discord server 

### ISSUE THREAD

**Issue by 32Red** [KarlOfDuty/SupportBoi#37]
i have no experience in code but i wanted to try it and this is the error message it gives me everytime i open the Supportboi_windows.exe: Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\m\Downloads\config.yml"

Unhandled Exception: YamlDotNet.Core.SyntaxErrorException: (Line: 12, Col: 5, Idx: 554) - (Line: 12, Col: 5, Idx: 554): While scanning a simple key, could not find expected ':'.
   at YamlDotNet.Core.Scanner.StaleSimpleKeys()
   at YamlDotNet.Core.Scanner.FetchMoreTokens()
   at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming()
   at YamlDotNet.Core.Parser.GetCurrentToken()
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by KarlOfDuty** [comment]
Put your config into a yaml validator.

**Comment by 32Red** [comment]
sorry, but how do i do that?

**Comment by KarlOfDuty** [comment]
https://lmgtfy.com/?q=yaml+validator&iie=1

**Comment by 32Red** [comment]
![image](https://user-images.githubusercontent.com/69594430/90044792-37c9a100-dcdf-11ea-8272-4ea42e714f8a.png)

**Comment by KarlOfDuty** [comment]
![image](https://user-images.githubusercontent.com/18099825/90045067-d39ee100-dcce-11ea-81f3-8eee346d90f0.png)

**Comment by KarlOfDuty** [comment]
I am not even sure where you got that from, that's not the config, thats not even yaml.

**Comment by 32Red** [comment]
lol it was in the support boi file

**Comment by 32Red** [comment]
could you send the original file if possible?

**Comment by KarlOfDuty** [comment]
Just delete it and run the bot again

**Comment by 32Red** [comment]
alright

**Comment by 32Red** [comment]
i re-installed it and 
![image](https://user-images.githubusercontent.com/69594430/90047767-85e0a380-dce3-11ea-856d-cc4d807683a2.png)

**Comment by 32Red** [comment]
same issue 😭

**Comment by KarlOfDuty** [comment]
I am very confused on what you are doing, just use the config the bot generates for you, stop putting code in it.

**Comment by 32Red** [comment]
so i write it in myself?

**Comment by KarlOfDuty** [comment]
I don't really know what you mean by that, you have to put in things like the bot token and command permissions yes

**Comment by 32Red** [comment]
can 
i use the Defualt config as a template?

**Comment by KarlOfDuty** [comment]
It is the thing you should edit, yes

**Comment by 32Red** [comment]
Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\32Red\Downloads\config.yml"

Unhandled Exception: YamlDotNet.Core.SyntaxErrorException: (Line: 12, Col: 5, Idx: 557) - (Line: 12, Col: 5, Idx: 557): While scanning a simple key, could not find expected ':'.
   at YamlDotNet.Core.Scanner.StaleSimpleKeys()
   at YamlDotNet.Core.Scanner.FetchMoreTokens()
   at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming()
   at YamlDotNet.Core.Parser.GetCurrentToken()
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.TryConsume[T](IParser parser, T& event)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 
i made it a yaml with the site and it still didnt work with this error message...

**Comment by 32Red** [comment]
oh wait i might know why

**Comment by 32Red** [comment]
Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\32Red\Downloads\config.yml"

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToUInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](IEnumerable`1 source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


hmm

**Comment by KarlOfDuty** [comment]
Just start from the default config and add one thing at a time, then you know what the issue is.

**Comment by 32Red** [comment]
i did that. i went threw it VERY carefully and i found nothing... and it gave me the same message error

**Comment by 32Red** [comment]
Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\32Red\Downloads\config.yml"

Unhandled Exception: System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by KarlOfDuty** [comment]
and what did you add to the config to make this happen? I recommend you just keep the default config and add your bot token for now.

**Comment by KarlOfDuty** [comment]
I'm not really sure how you are having so many issues with this, there are a lot of users of this bot and I don't think I have ever had anyone with this many issues before.

**Comment by 32Red** [comment]
hmm
do you have a default of just the emc supportboi? i can use that for now

**Comment by KarlOfDuty** [comment]
I can't just give out our passwords and auth tokens...

**Comment by 32Red** [comment]
oh

right

**Comment by KarlOfDuty** [comment]
Just add one thing, start the bot and see if it complains, then you know there is something wrong with the thing you added and you can tell me what that one thing is.

**Comment by 32Red** [comment]
ok

**Comment by KarlOfDuty** [comment]
I recommend starting with your bot token and then do database credentials as those are checked first.

**Comment by 32Red** [comment]
do i edit the log channel and stuff?

**Comment by KarlOfDuty** [comment]
no, just start with the token

**Comment by 32Red** [comment]
ok

**Comment by KarlOfDuty** [comment]
then do one thing at a time until it breaks

**Comment by 32Red** [comment]
ok
good plan

**Comment by 32Red** [comment]
Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\32Red\Downloads\config.yml"

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
 is the error i got after just putting in my token

**Comment by KarlOfDuty** [comment]
And what did you do?

**Comment by KarlOfDuty** [comment]
ah token

**Comment by 32Red** [comment]
ye

**Comment by 32Red** [comment]
there was nothing else i edited

**Comment by KarlOfDuty** [comment]
does it even work for you if you dont edit anything?

**Comment by 32Red** [comment]
i just put the token in lol everything else is default
but it didnt work

**Comment by KarlOfDuty** [comment]
like just delete everything from the bot folder except the application and start it again twice

**Comment by 32Red** [comment]
wait i didnt get it

**Comment by KarlOfDuty** [comment]
I will have to go now so you will have to keep trying on your own, good luck

**Comment by 32Red** [comment]
okay ill try cya

**Comment by KarlOfDuty** [comment]
if you start it once it creates the config and if you start it again it would try to read that config is what I mean, might be some issue with reading the config at all maybe

**Comment by KarlOfDuty** [comment]
but yeah cya and good luck

**Comment by 32Red** [comment]
ty

**Comment by 32Red** [comment]
ok i worked as hard as i could but i got greeted with this... Starting SupportBoi version 2.1.0-B...
Loading config "C:\Users\32Red\Downloads\config.yml"

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at SupportBoi.Config.LoadConfig()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by 32Red** [comment]
any help?

**Comment by KarlOfDuty** [comment]
I'm sorry but I have no idea how to help you, no one has had this issue before and I can't recreate it on my end either.

**Comment by KarlOfDuty** [comment]
Let me know if you find a solution though, this does sound pretty interesting.

**Comment by 32Red** [comment]
sad
