### ISSUE TITLE
unknown database error

### ISSUE THREAD

**Issue by sage-blue** [KarlOfDuty/SupportBoi#49]
on launching the program i get this error

Starting SupportBoi version 2.5.0...
Loading config "C:\Users\emil\Downloads\config.yml"
Connecting to database... (censored)
Could not set up database tables, please confirm connection settings, status of the server and permissions of MySQL user. Error: MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host 'censored' for user 'censored' using method 'mysql_native_password' failed with message: Unknown database 'censored' ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database 'censored'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SupportBoi.Database.SetupTables()
   at SupportBoi.SupportBoi.Reload()

Unhandled Exception: MySql.Data.MySqlClient.MySqlException: Authentication to host 'censored' for user 'censored' using method 'mysql_native_password' failed with message: Unknown database '' ---> MySql.Data.MySqlClient.MySqlException: Unknown database 'censored'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(Exception ex)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SupportBoi.Database.SetupTables()
   at SupportBoi.SupportBoi.Reload()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch(

not sure how to fix it,but i am sure the sql server info i entered in the config is correct.

**Comment by sage-blue** [comment]
fixed
